DROP DATABASE IF EXISTS aula08;
CREATE DATABASE IF NOT EXISTS aula08;
USE aula08;

CREATE TABLE cliente (
codigo CHAR(3) PRIMARY KEY,
nome VARCHAR(40) NOT NULL,
endereco VARCHAR(50) NOT NULL,
cidade VARCHAR(20) NOT NULL,
estado CHAR(2) NOT NULL,
cep CHAR(9) NOT NULL);

CREATE TABLE conta (
numero CHAR(6) PRIMARY KEY,
valor DECIMAL(10,2) NOT NULL,
vencimento DATE NOT NULL,
codcli CHAR(3) NOT NULL);

LOAD DATA INFILE 'C:/xampp/mysql/data/BD1-A08-conta.txt'
INTO TABLE conta
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;
